### PR TITLE
Update magicmirror-install.sh

### PR DESCRIPTION
**Pull request by ThellraAK**
Change connection prompt to allow bypass

Same as #856 and it's the only other one...  Sorry for not doing both at same time, I thought there was going to be a few and was just doing one to see if you'd be open to the change.

### CODE REVIEW

**Comment by tteck** [comment]
Thanks, don't know why those didn't get changed with the others.

**Comment by ThellraAK** [comment]
There are 17 that have don't have the check at all

> ~/Proxmox/setup $ grep -L  "Would you like to continue anyway? <y/N> " * | wc -l
17

Should I add the connection check in (early next week)?

**Comment by tteck** [comment]
They're only used in the `*-install.sh` you may be picking up the `*_setup.sh`

**Comment by ThellraAK** [comment]
Yep!

Thank you.

> grep -L  "Would you like to continue anyway? <y/N> " *-install.sh | wc -l
0

**Pull request merged**
