### PR TITLE
Adding Tandoor LXC

### PR DESCRIPTION
**Pull request by MickLesk**
## Description
I have prepared the Tandoor LXC.
It was a pain, the manual installation instructions were poor, faulty and sometimes just crap. 

I had to "take out" a lot of log output from the script by passing it to /dev/null 2>&1. Otherwise there would have been tens of hundreds of lines per query. Unfortunately, there was no other way to do it. If you do, please feel free to give feedback.

I have tested the LXC extensively. It took me many hours to finally get it running perfectly. 

For further information:
The RAM unfortunately has to be at 2048M because I always ran into a heapspace at 1024 and 1536 through vue and yarn. 

> https://github.com/tteck/Proxmox/discussions/50#discussioncomment-8527561 (latest, some other too)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix 
- [ ] New feature 
- [x] New Script
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
Great work! There's a lot of fine tuning to do.

**Comment by tteck** [comment]
When I get time, I'll place it in a dev branch to "fine tune"

**Comment by tteck** [comment]
@towerhand Ready to test before I merge.

```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/dev/ct/tandoor.sh)"
```

```
  ______                __                
 /_  __/___ _____  ____/ /___  ____  _____
  / / / __ `/ __ \/ __  / __ \/ __ \/ ___/
 / / / /_/ / / / / /_/ / /_/ / /_/ / /
/_/  \__,_/_/ /_/\__,_/\____/\____/_/

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: tandoor
Using Disk Size: 10
Allocated Cores: 4
Allocated RAM: 4096
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Tandoor LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Updated Python3
 ✓ Set up Node.js Repository
 ✓ Installed Node.js
 ✓ Installed Tandoor
 ✓ Set up PostgreSQL database
 ✓ Created Services
 ✓ Customized Container
 ✓ Cleaned
 ✓ Set Container to Normal Resources
 ✓ Completed Successfully!

Tandoor Setup should be reachable by going to the following URL.
         http://192.168.86.250:8002 
```

This thing is CPU hungry during the build process.

**Comment by towerhand** [comment]
No issues on my end. Thank you guys for the new script.

**Pull request merged**
