### PR TITLE
Add scripts for Calibre-web

### PR DESCRIPTION
**Pull request by remz1337**
## Description

[Calibre-web](https://github.com/janeczku/calibre-web) is a web app that offers a clean and intuitive interface for browsing, reading, and downloading eBooks. An alternative to Kavita that offers some additional feature such as LDAP user authentication.

## Type of change

Please delete options that are not relevant.

- [X] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [X] I have performed a self-review of my code, adhering to established codebase patterns and conventions.
- [X] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
Can the "CALIBRE-WEB OPTIONS" be moved to the `function update_script()`?

**Comment by remz1337** [comment]
Done. Added the ability to change selected options during update.

**Comment by tteck** [comment]
3 files?

**Comment by remz1337** [comment]
Fixed. Included unrelated commit by mistake

**Comment by MathijsG** [comment]
How can we set these options after installation? I have installed the calibre-web from this script but I didn't get any options. Now I seem to be missing the Kobo plugin.

**Comment by tteck** [comment]
Screenshot 2024-05-04 7 56 45 AM

**Pull request merged**
