### PR TITLE
Tweak: Fix Paperless Ghostscript

### PR DESCRIPTION
**Pull request by MickLesk**
## Description
Fix Ghostscript for Paperless to Stable 10.04.0 Version.
This Version is not in the debian repo, therefore i need to download from creator.

Fixes # (issue)
https://github.com/tteck/Proxmox/discussions/4002

## Type of change

- [x] Bug fix (non-breaking change that resolves an issue)
- [x] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Documentation update required (this change requires an update to the documentation)

### CODE REVIEW

**Comment by pepitoria** [comment]
There is still an issue with this one! I tried updating but ghostscript is still in version 10.00.0 in my paperless lxc.

what is going on is that the gs new version is installed in /usr/local/bin but the one in the path is in /usr/bin

right now this is as much as I can contribute, my bash scripting fu is not as high as I would like :/

**Comment by MickLesk** [comment]
You need to reboot after Update

**Comment by pepitoria** [comment]
yes, even after rebooting the container, my ghostscript in the lxc is still 10.00.0.

**Comment by MickLesk** [comment]
Post the complete Output after you Type the LXC Update. I cant see any Error. Tested 4 Times.

**Pull request merged**
