### PR TITLE
Add new LXC: Wastebin

### PR DESCRIPTION
**Pull request by MickLesk**
## Description

Wastebin is an personal Pastebin
https://github.com/matze/wastebin
We work with it a lot in our company and I have turned it into an LXC. 

## Type of change

Please delete options that are not relevant.

- [x] New Script
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
Deviates from the established patterns and conventions within our codebase.

**Comment by MickLesk** [comment]
And what exactly? I have taken 10 different scripts from you as a template, e.g. paperless, heimdall, plex, owncloud etc.. I see little to no difference.

I have the feeling you just don't want to accept any scripts from me.

**Comment by tteck** [comment]
`wastebin.sh`
1) `header_info` is not the correct styling 
2) Used `echo` where `msg_info` should be used

`wastebin-install.sh`

Deviates significantly from what I'd approve. 

I would accept your scripts if they align with the standards demonstrated by the scripts already present in the repository.
I conducted a code refactoring on your initial pull request (https://github.com/tteck/Proxmox/pull/2551/commits/3b9f4da4f1ec6de7072a401ba3d076ac0d5bbfef) to demonstrate these standards, with the intention of aiding your learning process.

> - It is important to stress that complaining about a decision after it has been made is not productive behavior for the pull request submitter. It is crucial for all contributors to respect the decision-making process and collaborate effectively towards achieving the best possible outcome for the project.

https://github.com/tteck/Proxmox/blob/main/.github/CONTRIBUTING.md

**Comment by MickLesk** [comment]
All good, it wasn't a complaint, it just always seems so negative / dismissive.

Unfortunately I don't know which ASCII styling you use. I couldn't find it anywhere, so I always used "doom" for my scripts because it looked similar.

Do you have a link or can you just say what "type" of ASCII you use for the headers?

Thanks for the correction! I'll take a look at it tomorrow & try to make the codes/scripts better.

Can I then resubmit/repull the script, or does it generally not fit your requirements?

**Comment by tteck** [comment]
https://www.patorjk.com/software/taag/#p=display&f=Slant&t=Wastebin

**Comment by tteck** [comment]
Something to look at:

```
bash <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) -y > /dev/null 2>&1
source ~/.cargo/env
```
```
RELEASE=$(curl -s https://api.github.com/repos/matze/wastebin/releases/latest | grep "tag_name" | awk '{print substr($2, 2, length($2)-3) }')
wget -q "https://github.com/matze/wastebin/archive/refs/tags/${RELEASE}.zip"
unzip -q ${RELEASE}.zip
mv wastebin-${RELEASE} /opt/wastebin
rm -R ${RELEASE}.zip 
cd /opt/wastebin
cargo build -q --release
```

**Comment by MickLesk** [comment]
I'm currently rebuilding it. I've found a few more little things. :-)

**Comment by tteck** [comment]
The Rust installation provided above, along with the instructions for setting up Wastebin, functions smoothly without encountering any problems.

**Comment by tteck** [comment]
Did you give up?

**Comment by MickLesk** [comment]
Nope, I'm just a bit ill and haven't been on the computer yet. The installer worked great for me too, I changed a bit of code but still have to check it in.

**Pull request closed without merging**
