### PR TITLE
Add GlitchTip

### PR DESCRIPTION
**Pull request by adaszko**
Hi, here's something I've been using locally and wanted to upstream.

## Description

Add a script for installing/updating https://glitchtip.com/

## Type of change

Please delete options that are not relevant.

- [X] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [X] I have performed a self-review of my code, adhering to established codebase patterns and conventions.

### CODE REVIEW

**Comment by tteck** [comment]
Sorry, not close to adhering to the established patterns and conventions.

**Comment by adaszko** [comment]
Which part though?

**Comment by tteck** [comment]
Look at any `*.sh` in `ct` and `*-install.sh` in `install`.

**Comment by adaszko** [comment]
It's based on that but oh well

**Pull request closed without merging**
