### PR TITLE
Add new LXC: NZBGet

### PR DESCRIPTION
**Pull request by havardthom**
> [!NOTE]
I am meticulous when it comes to merging code into the main branch, so please understand that I may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Requested: https://github.com/tteck/Proxmox/discussions/50#discussioncomment-10993027

[NZBGet](https://nzbget.com/) is an efficient, open-source Usenet software designed for downloading binary content from Usenet newsgroups. No matter how simple or complex your setup is, NZBGet is a lightweight application that has been optimized for speed and performance on any device.

Default login: nzbget | tegbzn6789

nzbget-installed
nzbget-updated
nzbget-ui

## Type of change

Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [x] New script (a fully functional and thoroughly tested script or set of scripts.)
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Documentation update required (this change requires an update to the documentation)

### CODE REVIEW

**Comment by tteck** [comment]
Why not use their APT repositories? https://nzbgetcom.github.io/

**Comment by havardthom** [comment]
Didn't know about them, can fix tomorrow

**Comment by havardthom** [comment]
Should be good now. Removed p7zip-full since 7zip is included in nzbget install.

**Comment by MickLesk** [comment]
> Should be good now. Removed p7zip-full since 7zip is included in nzbget install.

2GB und 2 Cores needed? Ive test it with 1GB/1C and I think its enough. :-)

**Pull request merged**
