### PR TITLE
Add Mafl Dashboard

### PR DESCRIPTION
**Pull request by hywax**
## Description

New dashboard added.
Repository - https://github.com/hywax/mafl

```
Mafl Interface: IP:3000
Config Path: /opt/mafl/data/config.yml
```

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix 
- [ ] New feature 
- [x] New Script
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
Have you tested this LXC creation?

**Comment by tteck** [comment]
I noticed that you're the creator of Mafl, but it seems that your Pull Request isn't functioning correctly. Would you like assistance in creating functional scripts?

**Comment by hywax** [comment]
Thank you very much! I'm not very good with bash scripts. I was looking at neighboring projects and repeating after them.

Now I executed the command and everything worked!

preview

**Comment by tteck** [comment]
What does Mafl stand for?

**Comment by BrutalCoding** [comment]
Why did your Twitter/X account get suspended @hywax? https://twitter.com/hywax_
I haven't been through the code, so I'm not sure whether this is safe or not. The documentation, from a quick glance, looks well structured and I like the modern design.

@tteck do you usually go through the code? Not just the bash script(s) but I mean the actual project. I just ask out of curiosity.

**Comment by tteck** [comment]
I thoroughly inspect everything to the best of my ability.

**Comment by hywax** [comment]
> Why did your Twitter/X account get suspended @hywax? https://twitter.com/hywax_ I haven't been through the code, so I'm not sure whether this is safe or not. The documentation, from a quick glance, looks well structured and I like the modern design.
> 
> @tteck do you usually go through the code? Not just the bash script(s) but I mean the actual project. I just ask out of curiosity.

I couldn't link my phone number there because twitter was blocked in my country. Because I don't have a phone number, twitter suspended my account.

**Comment by BrutalCoding** [comment]
> > Why did your Twitter/X account get suspended @hywax? https://twitter.com/hywax_ I haven't been through the code, so I'm not sure whether this is safe or not. The documentation, from a quick glance, looks well structured and I like the modern design.
> > @tteck do you usually go through the code? Not just the bash script(s) but I mean the actual project. I just ask out of curiosity.
> 
> I couldn't link my phone number there because twitter was blocked in my country. Because I don't have a phone number, twitter suspended my account.

Ah I see, sucks to hear that. Thanks for clarifying!

> I thoroughly inspect everything to the best of my ability.

Keep rocking on, your work has saved me quite some time. You should consider enabling GitHub Sponsorships.

**Pull request merged**
