### PR TITLE
Update docker-install.sh

### PR DESCRIPTION
**Pull request by slaclau**
Add Portainer agent

## Description
I have introduced the Portainer agent as an additional option for docker install. This would allow for multiple docker lxc instances to be managed with a single Portainer instance for centralised control.

## Type of change
- [x] New feature

### CODE REVIEW

**Comment by tteck** [comment]
Is it necessary to include an `if` statement to restrict the installation to either one option or the other?

**Comment by tteck** [comment]
```
read -r -p "Would you like to add Portainer? <y/N> " prompt
if [[ "${prompt,,}" =~ ^(y|yes)$ ]]; then
  msg_info "Installing Portainer $PORTAINER_LATEST_VERSION"
  docker volume create portainer_data >/dev/null
  $STD docker run -d \
    -p 8000:8000 \
    -p 9000:9000 \
    --name=portainer \
    --restart=always \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v portainer_data:/data \
    portainer/portainer-ce:latest
  msg_ok "Installed Portainer $PORTAINER_LATEST_VERSION"
else
  read -r -p "Would you like to add the Portainer Agent? <y/N> " prompt
  if [[ "${prompt,,}" =~ ^(y|yes)$ ]]; then
    msg_info "Installing Portainer agent $PORTAINER_AGENT_LATEST_VERSION"
    $STD docker run -d \
      -p 9001:9001 \
      --name portainer_agent \
      --restart=always \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /var/lib/docker/volumes:/var/lib/docker/volumes \
      portainer/agent
    msg_ok "Installed Portainer Agent $PORTAINER_AGENT_LATEST_VERSION"
  fi
fi
```

**Comment by tteck** [comment]
I will merge and then make the necessary changes.

**Comment by slaclau** [comment]
Thanks, the only reason I can think of for both is in case the main portainer server goes down - but I don't really think this is needed,

**Pull request merged**
