### PR TITLE
Add new LXC: Bookstack

### PR DESCRIPTION
**Pull request by MickLesk**
## Description

And a new script. I go through the discussions from time to time and build new scripts. Even if I don't need them. The community will be happy :-) 

In this case I have built Bookstack.
The LXC is quite resource-friendly, you are welcome to see if you want to reduce it a bit. In the same breath I have added the update script. This also works. I haven't noticed any bugs, but I'm not a hardcore user either.

Initial-Login (for your site):
User: admin@admin.com
Password: password

Request: https://github.com/tteck/Proxmox/discussions/50?sort=top#discussioncomment-2302511

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix 
- [ ] New feature 
- [x] New Script
- [ ] This change requires a documentation update

image

### CODE REVIEW

**Comment by MickLesk** [comment]
@tteck @towerhand Ready for Testing :-)

**Comment by MickLesk** [comment]
**In addition:** 
Bookstack requires a fixed IP or a URL.
Initially I query the current IP of the system after the LXC creation.

=> If someone switches the IP or changes to a URL, this must be done in 2 places:
- Apache2 - Config: /etc/apache2/sites-available/bookstack.conf (server name)
- Bookstack - Config: /opt/bookstack/.env (APP_URL)

**Comment by tteck** [comment]
There's a lot of work to do before this can be merged.

**Comment by MickLesk** [comment]
Feel Free, I make the scripts to the best of knowledge and conscience. Unfortunately I have no way of contacting you :-) 

In Germany we say: "nach besten Wissen und Gewissen" :-D

**Comment by tteck** [comment]
I'm currently unable to dedicate the time or effort needed to refactor all of your PRs. This particular one stands out as it deviates significantly from the established patterns and conventions within our codebase.

**Comment by MickLesk** [comment]
> I'm currently unable to dedicate the time or effort needed to refactor all of your PRs. This particular one stands out as it deviates significantly from the established patterns and conventions within our codebase.

Okay, too bad, then. Your comment didn't come across as particularly nice either. So, I'll save myself the trouble in the future and keep my scripts to myself if they're that bad. Clear feedback would have been more helpful in understanding exactly what you don't like. This just brings frustration, and it makes me lose the desire to provide scripts

**Comment by tteck** [comment]
I didn't mean to come across as offensive. If my words were interpreted that way, I apologize.

**Comment by tteck** [comment]
Besides, you use the "TurnKey LXC Appliances" script to create a Bookstack LXC.

**Pull request closed without merging**
