### PR TITLE
Update wireguard-install.sh

### PR DESCRIPTION
**Pull request by Eylexander**
## Description

I just made some small changes about the installation of Wireguard LXC where you can edit the default settings of PiVPN.

## Type of change

Please delete options that are not relevant.

- [ ] New feature

### CODE REVIEW

**Comment by tteck** [comment]
How can you edit the default settings? All that I see is a y/n question.

**Comment by Eylexander** [comment]
Actually i do it in a "dirty" way with nano, where you can update default settings.

I do believe after a second read that I could have just create the file i edit it if needed.

**Comment by Eylexander** [comment]
Does changing the install parameters of pivpn isn't to be considered ?

**Comment by tteck** [comment]
Sure, if you can clearly explain why.

**Comment by tteck** [comment]
~With your PR, you're just excluding parameters, not editing them.~

**Comment by tteck** [comment]
Oh, I now see what you've done. Yeah that doesn't work for me, sorry.

**Comment by Eylexander** [comment]
Originally, I wanted to install Wireguard with specific settings like port or DNS, but post-installation changes are much more complicated than when installing. That's why I think adding this option could be more interesting than having to do it by hand.
(Actually this is my first pull request so I'm a bit lost)

**Comment by Eylexander** [comment]
Still lost and would really want to understand how to do it right (actually even if not possible to merge). Because i don't believe nano is a good fit.

**Pull request closed without merging**
