### PR TITLE
smokeping lxc container

### PR DESCRIPTION
**Pull request by tnware**
## Description

Added [SmokePing](https://oss.oetiker.ch/smokeping/stats.en.html) LXC Container
Needs gh-pages info

Is functional out of the box, requires normal smokeping config steps.

[Config Examples](https://oss.oetiker.ch/smokeping/doc/smokeping_examples.en.html)
[Config Docs](https://oss.oetiker.ch/smokeping/doc/smokeping_config.en.html)

for example, basic setup;

`nano /etc/smokeping/config.d/Targets`

append targets
```
++ DefaultRouter0

menu = Router 192.168.0.1
title = 192.168.0.1 ICMP Latency
host = 192.168.0.1

++ Cloudflare

menu = Cloudflare 1.1.1.1
title = 1.1.1.1 ICMP Latency
host = 1.1.1.1
```

`systemctl restart smokeping`

SmokePing has a default 5min polling interval, so users won't see data immediately, but all product knowledge should of course be handled through the relevant documentation as this is just an installation script to kick-start an instance.

## Type of change

- [x] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [x] I have performed a self-review of my code, adhering to established codebase patterns and conventions.
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
Why not just `apt-get install -y smokeping` in a Debian container and modify the conf files at `/etc/smokeping/config.d/`
I don't see the need for installing any additional packages or executing any extra commands.

**Comment by tteck** [comment]
Perhaps I could include an option in the Uptime Kuma LXC to install Smokeping. I simply don't believe it requires its own LXC for such a straightforward application.

**Comment by tnware** [comment]
I think i misunderstood what your purpose behind this utility.

> These scripts empower users to create a Linux container or virtual machine interactively

I'm not sure what is so complicated about the other containers that makes them more eligible for an interactive LXC script. such as postgres, grafana, influx, or probably 85% of your other offerings, however to fully utilize SmokePing is not as simple as just installing smokeping on apt, you need to configure apache to serve CGI scripts.

Anyways, good luck with your repository of debian LXC image that can have software installed atop it.

**Comment by tteck** [comment]
Smokeping is as simple as `apt-get install -y smokeping`, no need to do anything else but modify the config files.

**Comment by tnware** [comment]
tteck, with all due respect, please serve me up an instance of smokeping with the apt install, and publish the URL when you are done.

this is not even important, though.

you're advertising a platform that allows users to spin up LXC containers interactively.

what is the qualifier for what meets the standards of an LXC container interactive installation? 

"I am meticulous when it comes to merging code into the main branch"

I originally thought this was about code-quality and conformity, but it appears as though its arbitrary as to what you feel is necessary or not.

If everyone in the world projected their skill set onto others, there would be no "interactive proxmox scripts" like you're hosting here.

again, good luck with your repository. nothing to contribute to here.

**Comment by tteck** [comment]
>tteck, with all due respect, please serve me up an instance of smokeping with only the apt install, and publish the URL when you are done.

Just create a Debian 12 LXC, then execute `apt-get install -y smokeping` in the console. After the installation is complete, go to `IP/smokeping`. You will then see that it **is** that simple.

**Comment by tnware** [comment]
My intention with the proposed script was to align with the overarching goal of your repository to facilitate a user-friendly and interactive approach to setting up various services, not just for expert users but for beginners as well.

The beauty of your repository lies in its ability to demystify this process, to turn what could be a complex setup into a series of simple, guided steps; along with discovery of new things to explore.

The catalog you offer; the proxmox maintenance scripts are great, and the LXC containers are a fun way to discover packages and quickly deploy them for testing. If you're not interested in your repository being used for discovery of new packages and ease of deployment, I completely understand that, and will focus my contributions to those repositories that welcome this.

Thank you.

**Comment by tteck** [comment]
Based on the new information I've provided, do you now understand that your proposed script doesn't meet the "code-quality and conformity" standards expected by this repository?

Oh, here's a good read for you, https://github.com/tteck/Proxmox/blob/main/.github/CONTRIBUTING.md

**Comment by tnware** [comment]
a recommended addition:
"don't submit packages if they don't require any configuration, github downloads, or external repos"

literally no one is complaining.

you're acting like I didn't read your repository up and down before contributing

but really you're just unable to articulate what the goal of your project is, and you call that "meticulous" and follow that up with pinning anyone who doesn't understand it as "complaining" and it's so palpable that you need to write it in your contributing guidelines, yet it's still unclear.

sad

**Comment by tteck** [comment]
Now that I have a bit of spare time, I thought I'd offer an example of what could have been merged, using example targets:

```
#!/usr/bin/env bash

source <(curl -s https://raw.githubusercontent.com/tteck/Proxmox/main/misc/build.func)
# Copyright (c) 2021-2024 tteck
# Author: tteck (tteckster)
# License: MIT
# https://github.com/tteck/Proxmox/raw/main/LICENSE

function header_info {
clear
cat <<"EOF"
   _____                 __        ____  _
  / ___/____ ___  ____  / /_____  / __ \(_)___  ____ _
  \__ \/ __ `__ \/ __ \/ //_/ _ \/ /_/ / / __ \/ __ `/
 ___/ / / / / / / /_/ / ,< /  __/ ____/ / / / / /_/ /
/____/_/ /_/ /_/\____/_/|_|\___/_/   /_/_/ /_/\__, /
                                             /____/
EOF
}
header_info
echo -e "Loading..."
APP="SmokePing"
var_disk="2"
var_cpu="1"
var_ram="512"
var_os="debian"
var_version="12"
variables
color
catch_errors

function default_settings() {
  CT_TYPE="1"
  PW=""
  CT_ID=$NEXTID
  HN=$NSAPP
  DISK_SIZE="$var_disk"
  CORE_COUNT="$var_cpu"
  RAM_SIZE="$var_ram"
  BRG="vmbr0"
  NET="dhcp"
  GATE=""
  APT_CACHER=""
  APT_CACHER_IP=""
  DISABLEIP6="no"
  MTU=""
  SD=""
  NS=""
  MAC=""
  VLAN=""
  SSH="no"
  VERB="no"
  echo_default
}

function update_script() {
header_info
if ! command -v smokeping &> /dev/null; then msg_error "No ${APP} Installation Found!"; exit; fi

msg_info "Updating ${APP}"
apt-get update &>/dev/null
apt-get -y upgrade &>/dev/null
msg_ok "Updated Successfully"
exit
}

start
build_container
description

msg_ok "Completed Successfully!\n"
echo -e "${APP} should be reachable by going to the following URL.
         ${BL}http://${IP}/smokeping${CL} \n"
```

```
#!/usr/bin/env bash

# Copyright (c) 2021-2024 tteck
# Author: tteck (tteckster)
# License: MIT
# https://github.com/tteck/Proxmox/raw/main/LICENSE

source /dev/stdin <<< "$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

msg_info "Installing Dependencies"
$STD apt-get install -y curl
$STD apt-get install -y sudo
$STD apt-get install -y mc
msg_ok "Installed Dependencies"

msg_info "Installing SmokePing"
$STD apt-get install -y smokeping
cat <<EOF >/etc/smokeping/config.d/Targets
*** Targets ***
probe = FPing
menu = Top
title = Network Latency Grapher
remark = Welcome to SmokePing.
+ Local
menu = Local
title = Local Network (ICMP)
++ LocalMachine
menu = Local Machine
title = This host
host = localhost
+ DNS
menu = DNS latency
title = DNS latency (ICMP)
++ Google
title = Google
host = 8.8.8.8
++ Cloudflare
title = Cloudflare
host = 1.1.1.1
++ Quad9  
title = Quad9 
host = 9.9.9.9
++ OpenDNS
title = OpenDNS
host = 208.67.222.222
+ HTTP
menu = HTTP latency
title = HTTP latency (ICMP)
++ Github
host = github.com
++ Discord
host = discord.com
++ Google
host = google.com
++ Cloudflare
host = cloudflare.com
++ Amazon
host = amazon.com
++ Netflix
host = netflix.com
EOF
systemctl restart smokeping
msg_ok "Installed SmokePing"

motd_ssh
customize

msg_info "Cleaning up"
$STD apt-get autoremove
$STD apt-get autoclean
msg_ok "Cleaned"
```
If you're inclined to implement these adjustments, I'm more than willing to proceed with the merge. Alternatively, if you prefer not to proceed, I can go ahead and create the scripts.

**Comment by tteck** [comment]
Added

**Pull request closed without merging**
