### PR TITLE
Update vaultwarden-install.sh

### PR DESCRIPTION
**Pull request by schiz0phr3ne**
Enable all backends, and not only SQLite

### CODE REVIEW

**Comment by tteck** [comment]
The reason that I only enable the self contained SQLite db is so that a backup saves/restores all data.

**Comment by schiz0phr3ne** [comment]
I understand.

We have 3 options :
- enable other backends, and warn about backups with other than SQLite
- don't enable other backends, but add an information for advanced users that only SQLite backend is enabled
- stay as we are ^^

It's up to you

**Comment by tteck** [comment]
IINM, an external database can be defined in the `/etc/vaultwarden.env`

**Comment by schiz0phr3ne** [comment]
We have this error message when using `DATABASE_URL` with MySQL, when MySQL is not an enabled backend : `'DATABASE_URL' is a MySQL URL, but the 'mysql' feature is not enabled`

**Comment by schiz0phr3ne** [comment]
`- Building Vaultwarden (Patience)...‼ ERROR 101@100 Unknown failure occured.` with script updated on my repository, will check about that

**Comment by tteck** [comment]
Try, `cargo build --features "sqlite,mysql,postgresql"`

**Comment by schiz0phr3ne** [comment]
It's about this error : `/usr/bin/ld: cannot find -lmysqlclient` (I only try with MySQL for the moment).

Official repository state this for MySQL and PostgreSQL : 
```
- For the MySQL backend on a Debian based distro you need to install libmariadb-dev-compat and libmariadb-dev
- For the PostgreSQL on a Debian based distro you need to install libpq-dev and pkg-config 
```

I'll try this afternoon.

**Comment by tteck** [comment]
`pkg-config` is already a prerequisite

**Comment by tteck** [comment]
Working on a fix in branch vault.

**Comment by schiz0phr3ne** [comment]
Outside right now, but I also achieved a build.
I will check if all is working with MySQL.

**Comment by schiz0phr3ne** [comment]
I get an error with you script, but maybe I don't call it properly ?

```
# bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/blob/vault/ct/vaultwarden-v3.sh)"
-bash: /usr/bin/bash: Argument list too long
```

Mine is working here, I have my vault with MySQL working fine.

**Comment by tteck** [comment]
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/vault/ct/vaultwarden-v3.sh)"
```
yeah, I'm still working on a complete code refactoring, so it's not complete yet

**Comment by schiz0phr3ne** [comment]
Let me know when I can test to help you, with MySQL _a minima_

**Comment by tteck** [comment]
Ready for testing. 🤞🏻 
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/vault/ct/vaultwarden-v3.sh)"
```
The working directory is now `/opt/vaultwarden`
Which means the environment file has moved to `/opt/vaultwarden/.env` 
`ROCKET_ADDRESS=0.0.0.0` is preset
Check all available settings in the [env.template](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template)  if needed
The script automatically sets the container resources to normal settings after the build

**Comment by schiz0phr3ne** [comment]
Got an error during Vaultwarden building : `- Building Vaultwarden *Reminder* (Patience)...‼ ERROR 1@99 Unknown failure occured.`

**Comment by tteck** [comment]
Strange, I've completed the script 3 times without error.
I commented out @99 (`git checkout refs/tags/$VAULT`) should pass

**Comment by schiz0phr3ne** [comment]
Everything is working fine, except that some default folders are miswritten : 

image

**Comment by schiz0phr3ne** [comment]
Line 118 : `DATA_FOLDER=/opt/vaultwarden/data/` → maybe the trailing slash

**Comment by schiz0phr3ne** [comment]
Yep, just need to delete the trailing slash from `.env`, restart service and everything is fine (or seems to be).

**Comment by tteck** [comment]
In main branch
Thank you for your help!

**Comment by schiz0phr3ne** [comment]
Thank you for your work !

**Pull request closed without merging**
