### PR TITLE
iVentoy

### PR DESCRIPTION
**Pull request by DrEVILish**
## Description
Created Install Script for iVentoy using other tteck scripts as templates. 

Unable to test full script due to scripts multiple hard-coded links, to GitHub repos. (Totally understand if you reject PR.) If there is a standard way for creating and testing these scripts, I'd appreciate a nudge.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [ ] I have performed a self-review of my code, adhering to established codebase patterns and conventions.
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
These types of scripts are a support nightmare. I'd rather avoid these.

**Comment by tteck** [comment]
I'm rethinking this...

**Comment by DrEVILish** [comment]
Happy to have a discussion opened about it.
Tried to keep it clean, tho testing the PR is difficult with the hardcoded github repo links.

**Comment by tteck** [comment]
Well now it has an additional file attached to the PR. `misc/arr-update.sh`

**Pull request closed without merging**
