### PR TITLE
Hint for right URL added on v2

### PR DESCRIPTION
**Pull request by nicedevil007**
make script more consistent to other scripts

## Type of change

- [X] Bug fix

### CODE REVIEW

**Comment by tteck** [comment]
Not needed, shown in instructions.

**Comment by nicedevil007** [comment]
when that is not needed then all other scripts have them in instructions as well and show the hint after completion?
not consistent :P

**Comment by tteck** [comment]
Compared to other scripts, this particular one stands out because it provides version choices, with one version featuring a GUI and the other lacking it.

**Comment by nicedevil007** [comment]
thats why I added the hint as you did in your instruction but ok your decision but makes me upset.... sometimes it is ok making things more consistent accross all scripts and sometimes not that makes contributing a bit frustrating here and there

**Comment by tteck** [comment]
While it is true that the decision to accept or decline a pull request ultimately rests with the project maintainer, it is important to stress that complaining about the decision after it has been made is not productive behavior for the pull request submitter. It is crucial for all contributors to respect the decision-making process and collaborate effectively towards achieving the best possible outcome for the project.

**Pull request closed without merging**
