### PR TITLE
Add new LXC: ArchiveBox

### PR DESCRIPTION
**Pull request by MickLesk**
### Add new Script ArchiveBox.

After installation (optionally) need to run: 
```
cd /opt/archivebox/data
sudo -u archivebox archivebox setup 
```

for the automatic setup with admin-user

or: 
```
cd /opt/archivebox/data
sudo -u archivebox archivebox manage createsuperuser
```
for only create an superuser.

image

## Type of change
- [x] New script (a fully functional and thoroughly tested script or set of scripts.)
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Documentation update required (this change requires an update to the documentation)

image

### CODE REVIEW

**Comment by tteck** [comment]
Does not adhere to the established patterns and conventions

**Comment by MickLesk** [comment]
> Does not adhere to the established patterns and conventions

That makes me lose my enthusiasm. You can save such a stupid remark. Then I'll quit here and that's it.

**Comment by tteck** [comment]
I appreciate your contributions, but I've noticed that most of your pull requests require a lot of corrections. It would be great if you could take a bit more time to understand the code and avoid relying on copy/paste. This will help with my frustrations/time constraints. Thank you!

**Comment by tteck** [comment]
Something to consider. Tested in a fresh Debian 12 LXC.

```
echo "Installing Dependencies..."
apt-get install -y \
  curl \
  sudo \
  mc \
  git \
  expect \
  libssl-dev \
  libldap2-dev \
  libsasl2-dev \
  procps \
  dnsutils \
  ripgrep
echo "Installed Dependencies"

echo "Installing Python Dependencies..."
apt-get install -y \
  python3-pip \
  python3-ldap \
  python3-msgpack \
  python3-regex
echo "Installed Python Dependencies"

echo "Installing Node.js..."
mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" >/etc/apt/sources.list.d/nodesource.list
apt-get update
apt-get install -y nodejs
echo "Installed Node.js"

echo "Installing Playright..."
pip install playwright
playwright install --with-deps chromium
echo "Installed Playright"

echo "Installing ArchiveBox..."
mkdir -p /opt/archivebox/{data,.npm,.cache,.local}
adduser --system --shell /bin/bash --gecos 'Archive Box User' --group --disabled-password  archivebox
chown -R archivebox:archivebox /opt/archivebox/{data,.npm,.cache,.local}
chmod -R 755 /opt/archivebox/data
pip install archivebox
cd /opt/archivebox/data
expect <<EOF
set timeout -1
spawn sudo -u archivebox archivebox setup

expect "Username"
send "\r"

expect "Email address"
send "\r"

expect "Password"
send "helper-scripts.com\r"

expect "Password (again)"
send "helper-scripts.com\r"

expect eof
EOF
echo "Installed ArchiveBox"

echo "Creating Service..."
cat <<EOF >/etc/systemd/system/archivebox.service
[Unit]
Description=ArchiveBox Server
After=network.target

[Service]
User=archivebox
WorkingDirectory=/opt/archivebox/data
ExecStart=/usr/local/bin/archivebox server 0.0.0.0:8000
Restart=always

[Install]
WantedBy=multi-user.target
EOF
systemctl enable -q --now archivebox.service
echo "Created Service"
```

`http://<IP>:8000/admin/login/`
Username: `archivebox`
Password: `helper-scripts.com`

**Comment by tteck** [comment]
https://github.com/ArchiveBox/ArchiveBox/wiki/Upgrading

**Pull request closed without merging**
