### PR TITLE
iVentoy - updated

### PR DESCRIPTION
**Pull request by DrEVILish**
## Description

Created Install Script for iVentoy using other tteck scripts as templates. (added it's own branch this time, sorry)

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [x] I have performed a self-review of my code, adhering to established codebase patterns and conventions.
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
First try:

```
    _ _    __           __             
   (_) |  / /__  ____  / /_____  __  __
  / /| | / / _ \/ __ \/ __/ __ \/ / / /
 / / | |/ /  __/ / / / /_/ /_/ / /_/ / 
/_/  |___/\___/_/ /_/\__/\____/\__, /  
                              /____/

Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 110
Using Hostname: iventoy
Using Disk Size: 2
Allocated Cores: 1
Allocated RAM: 512
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Using APT-Cacher IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a iVentoy LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using thin-pool for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 110 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.250 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.112.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed iVentoy
 - Creating Service  \
[ERROR] in line 51: exit code 0: while executing command systemctl enable --now -q iventoy.service
root@server:~#

**Comment by tteck** [comment]
>  New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)

There is no way this is accurate.

**Comment by tteck** [comment]
Files deleted. **Non-functional**

**Comment by DrEVILish** [comment]
The testing I've been able to do doesn't error on my side.
How am I supposed to do full test with the hardcoded GitHub links?

**Pull request merged**
