### PR TITLE
Adding Unpackerr as script

### PR DESCRIPTION
**Pull request by kloknibor**
# All Pull Requests should be made to the `pull-requests` branch

## Description

Adding unpackerr as script

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x ] New Script
- [ x ] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
Instead of adding an Ubuntu source repository (https://packagecloud.io/golift/pkgs/ubuntu focal InRelease) using a curl-bash script that is beyond my control, why not use the Debian Software Package file to eliminate this dependency?

**Comment by tteck** [comment]
This example is using the Debian Software Package file to install the software, which ensures that the latest release is being installed.
```
RELEASE=$(curl -s https://api.github.com/repos/Unpackerr/unpackerr/releases/latest | grep -o 'unpackerr_.*\_amd64.deb' | head -n 1)
wget -q https://github.com/Unpackerr/unpackerr/releases/latest/download/$RELEASE
$STD dpkg -i $RELEASE
rm $RELEASE
```
Using the example above, the need for dependencies `git` and `gnupg` is eliminated.

The `unpackerr.service` is already enabled and started, which means that line 96 in `unpackerr-v5-install.sh` can be removed.

The command on line 338 in `unpackerr-v5.sh` must be corrected to `if ! command -v pveversion >/dev/null 2>&1 && [[ ! -f /etc/unpackerr/unpackerr.conf ]]; then`.

Although this is just a matter of preference, it helps maintain consistency in the appearance.
```
   __  __                       __                 
  / / / /___  ____  ____ ______/ /_____v5__________
 / / / / __ \/ __ \/ __ `/ ___/ //_/ _ \/ ___/ ___/
/ /_/ / / / / /_/ / /_/ / /__/ ,< /  __/ /  / /    
\____/_/ /_/ .___/\__,_/\___/_/|_|\___/_/  /_/     
          /_/                                      

```

Thank you for your hard work in creating the helper script. However, to maintain the quality and consistency of the files, I will be closing this pull request. If you would like, you can make the necessary corrections and submit the updated files. Alternatively, if you decide not to continue, please let me know and I will create the script myself.

**Comment by kloknibor** [comment]
Hi tteck,

thanks for your feedback to improve this implementation. I'll see if I have some time to improve it in the coming days.

**Comment by kloknibor** [comment]
I currently can't get this properly to work due to permission issues. Unpackerr runs as user and group unpackerr:unpackerr with ID's 998:998 (inside LXC), but all the files on host are 1000:1000 (so 101000 101000 within the LXC due to container being unpriviliged)

I tried to play with the user mappings but I haven't found a safe-ish solution for this to work. The problem is that unpackerr needs to be able to write in mount points (in this case nfs mounts to the host).

You have any suggestion to get this to play nice?

**Comment by tteck** [comment]
What are the results when you run the container with privileged mode enabled?

**Comment by kloknibor** [comment]
I got frustrated and chmodded everything 777 on my nas since it are temp files anyway... (for some reason also 755 gave issues). When I have a freshly downloaded file I will check how it performs with a privileged container. Potentially with a privileged container the NFS volume could be mounted directly anyway.

**Comment by oscarsantillana** [comment]
Any chance to revisit this PR?

**Comment by tteck** [comment]
@oscarsantillana, The current state of this pull request is far from ready to be merged into the main branch. It requires a complete overhaul.

**Pull request closed without merging**
