### PR TITLE
Support frigate latest release (v14)

### PR DESCRIPTION
**Pull request by remz1337**
## Description

Add tempio installation and prepend timestamp to all service logs so that frigate can parse them

## Type of change

- [x] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [x] I have performed a self-review of my code, adhering to established codebase patterns and conventions.

### CODE REVIEW

**Comment by Vendo233** [comment]
Hi , what is the new Command to install Frigate 14?

**Comment by lasharor** [comment]
How do I update an LXC already running frigate?

**Comment by jmcruvellier** [comment]
For those who are looking for the commands to update Frigate:
```
cd /opt 
docker compose pull 
docker compose up -d 
```
Make sure to perform a backup of frigate configuration file and database before,

**Comment by lasharor** [comment]
> For those who are looking for the commands to update Frigate:
> 
> ```
> cd /opt 
> docker compose pull 
> docker compose up -d 
> ```
> 
> Make sure to perform a backup of frigate configuration file and database before,

This doesn't work on the LXC created by the previous script. As the docker-compose refers to the old frigate build. Is there a way to update the LXC which was created using the old script?

**Comment by jmcruvellier** [comment]
> > For those who are looking for the commands to update Frigate:
> > 
> > ```
> > cd /opt 
> > docker compose pull 
> > docker compose up -d 
> > ```
> > 
> > Make sure to perform a backup of frigate configuration file and database before,
> 
> This doesn't work on the LXC created by the previous script. As the docker-compose refers to the old frigate build. Is there a way to update the LXC which was created using the old script? 

On the Frigate LXC console, try to execute "update" command

**Comment by lasharor** [comment]
> > > For those who are looking for the commands to update Frigate:
> > > ```
> > > cd /opt 
> > > docker compose pull 
> > > docker compose up -d 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Make sure to perform a backup of frigate configuration file and database before,
> > 
> > 
> > This doesn't work on the LXC created by the previous script. As the docker-compose refers to the old frigate build. Is there a way to update the LXC which was created using the old script?
> 
> On the Frigate LXC console, try to execute "update" command

 ✗ There is currently no update path available.

**Pull request merged**
