### PR TITLE
Fix Peanut script following latest release (v3)

### PR DESCRIPTION
**Pull request by remz1337**
> [!NOTE]
I am meticulous when it comes to merging code into the main branch, so please understand that I may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description
Fix Peanut script following latest release (v3)
Peanut is now looking for a settings.yml file upon start up, where environment configs are stored. File is created with default values.

Fixes https://github.com/tteck/Proxmox/discussions/3937#discussioncomment-11019492

## Type of change

Please check the relevant option(s):

- [X] Bug fix (non-breaking change that resolves an issue)
- [X] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)

### CODE REVIEW

**Comment by tteck** [comment]
Screenshot 2024-10-22 4 43 05 PM

**Comment by remz1337** [comment]
yes, simply click on the exit (red button) and it will bring you to the home page where you can fill in the server. Not sure if we can bypass this @Brandawg93

**Comment by tteck** [comment]
After filling in the server

Screenshot 2024-10-22 4 50 21 PM

**Comment by Brandawg93** [comment]
Ya this is bothering others too. Let me take a look.

**Comment by remz1337** [comment]
@tteck if you put in the default (localhost) NUT server, you still need to configure NUT with your UPS. In my case, I have NUT running in a separate LXC, and when putting in the IP and port of that NUT server, peaNUT is working fine
image

**Comment by Brandawg93** [comment]
Ok. Quick fix for those who haven't added a volume in docker yet: https://hub.docker.com/layers/brandawg93/peanut/test/images/sha256-97f0b415884d93d5f77ebc9fdf83d4d563cf1556d422abe60eddcc124e59f504?context=repo

Could someone try this test version and see if it works?

**Comment by Brandawg93** [comment]
P.S. you _should_ be able to just delete your settings.yml and remove the docker volumes and let the environment variables do everything for you. Of course, any changes will not persist between containers. But this would give better backwards compatibility to v2.

**Pull request merged**
