### PR TITLE
Add support for postgresql DB and fail2ban in vaultwarden

### PR DESCRIPTION
**Pull request by remz1337**
## Description

Added support for postgresql and fail2ban to vaultwarden. Both are optional and can be enabled/disabled during install script.
I also added a token generation function (pass length as first argument, otherwise defaults to 30), which is used to generate both the vaultwarden admin token and the password of the vaultwarden postgres user

## Type of change

- [x] New feature

### CODE REVIEW

**Comment by tteck** [comment]
The current "Set Admin Token" method is preferred.

**Comment by remz1337** [comment]
Hey @tteck, I know this PR introduces quite a few changes. Did you close the PR because you are not interested in any of those changes (adding fail2ban and postgresql support)? Because if it's just the set admin token part, I can drop that commit and keep the rest.

**Comment by tteck** [comment]
I'm satisfied with the current structure of the script.

**Comment by AntiApple4life** [comment]
Do you think that this could be added as a third option in addition debian and alpine vaultwarden scripts?

**Comment by remz1337** [comment]
> Do you think that this could be added as a third option in addition debian and alpine vaultwarden scripts?

@Anti-Apple4life script is still available in my fork (https://github.com/remz1337/Proxmox)

**Pull request closed without merging**
