### PR TITLE
Adding more support and little feature

### PR DESCRIPTION
**Pull request by Gauvino**
Just adding support of other os and the hostname in the info bar

Please delete options that are not relevant.

- [Update Ubuntu, Debian, Devuan, Alpine Linux, CentOS-Rocky-Alma, Fedora, ArchLinux ] New feature

### CODE REVIEW

**Comment by tteck** [comment]
Thanks!

**Comment by Gauvino** [comment]
do you think i can make a version with no prompt like for cron tab or else ?

**Comment by tteck** [comment]
For your personal use?  YES, that can be easily accomplished.

**Comment by QrchackOfficial** [comment]
just FIY, this line broke Alpine support

https://github.com/tteck/Proxmox/pull/755/commits/4b2148b5fb67a9f80618dcc5177b98ef1c94b5f2#diff-945bb1ebe578e6bc1904231845179165e6dc52253774be86021fa151f194cbd3R42

```
pct exec $container -- ash -c "apk update && apk upgrade -y"
```

results in:

```
[Info] Updating 101 : dolores

fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
v3.16.3-13-g4d933a1fa3 [https://dl-cdn.alpinelinux.org/alpine/v3.16/main]
v3.16.3-16-g3d31a554be [https://dl-cdn.alpinelinux.org/alpine/v3.16/community]
OK: 17045 distinct packages available
apk: unrecognized option: y
```

a list of flags is given and apk terminates without updating, along with the whole script

**Comment by QrchackOfficial** [comment]
also known as "don't slap -y to every package manager, not everyone is Ubuntu"

**Comment by QrchackOfficial** [comment]
Added https://github.com/tteck/Proxmox/pull/781

**Pull request merged**
