### PR TITLE
Add New LXC: Ollama

### PR DESCRIPTION
**Pull request by ulmentflam**
## Description

This PR adds Ollama as an LXC. Ollama is a self-hosted API for running large language models. It supports the open Llama Models, Phi, Minstral, Gemma, and more. This LXC benefits from GPU passthrough and installation of GPU drivers. 

## Type of change

- [x] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [x] I have performed a self-review of my code, adhering to established codebase patterns and conventions.
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
1. You have not adhered to established codebase patterns and conventions.
2. This will be a nightmare with the way it's installing NVIDIA and AMD drivers "WSL2 only supports GPUs via nvidia passthrough" No thank you.
3. Executing https://ollama.com/install.sh inside another bash script is frowned upon.

Just not interested, sorry.

**Comment by ulmentflam** [comment]
Okay, No problem. I apologize for not adhering to the conventions. 

I could have also gone through the manual install steps from https://github.com/ollama/ollama/blob/main/docs/linux.md#manual-install which just installs the binary and doesn't install the Nvidia or AMD drivers and leaves the WSL2 passthrough up to the installer. 

Out of curiosity what conventions did I miss besides using Ollama's install.sh, script inside of another bash script?

**Comment by tteck** [comment]
header_info

**Comment by ulmentflam** [comment]
I see, you use the slant ASCII font https://github.com/tteck/Proxmox/pull/2605#issuecomment-1979668948. Thanks! 

Also thanks for maintaining this, it is fantastic!

**Pull request closed without merging**
