### PR TITLE
Enable ZFS + reuse downloaded file

### PR DESCRIPTION
**Pull request by enoch85**
## I wanted to make you aware that I am meticulous when it comes to merging code into the main branch, so please don't take it personally if I reject your request.

I hear you. :)

## Description

Trying to install this for the first time on my ZFS system - it failed. When I later added the option for ZFS, it downloaded the file again which seems unnecessary.  

## Fixes

This adds support for "local-zfs" (standard name) and reuses the downloaded file instead of hammering on Githubs servers. It's also better for people on slow connections, trying again will be faster.

## Type of change

- [X] Bug fix 
- [X] New feature

### CODE REVIEW

**Comment by enoch85** [comment]
This is now ready to review.

Thanks!

**Comment by tteck** [comment]
The script already functions with local-zfs without modifications.

```
    __  __                        ___              _      __              __     ____  _____
   / / / /___  ____ ___  ___     /   |  __________(_)____/ /_____ _____  / /_   / __ \/ ___/
  / /_/ / __ \/ __ `__ \/ _ \   / /| | / ___/ ___/ / ___/ __/ __ `/ __ \/ __/  / / / /\__ \
 / __  / /_/ / / / / / /  __/  / ___ |(__  |__  ) (__  ) /_/ /_/ / / / / /_   / /_/ /___/ /
/_/ /_/\____/_/ /_/ /_/\___/  /_/  |_/____/____/_/____/\__/\__,_/_/ /_/\__/   \____//____/

Using Default Settings
Using HAOS Version: 11.0
Using Virtual Machine ID: 102
Using Machine Type: i440fx
Using Disk Cache: Write Through
Using Hostname: haos11.0
Using CPU Model: Host
Allocated Cores: 2
Allocated RAM: 4096
Using Bridge: vmbr0
Using MAC Address: 02:C2:70:E5:CF:A7
Using VLAN: Default
Using Interface MTU Size: Default
Start VM when completed: yes
Creating a HAOS VM using the above default settings
 ✓ Using local-zfs for Storage Location.
 ✓ Virtual Machine ID is 102.
 ✓ https://github.com/home-assistant/operating-system/releases/download/11.0/haos_ova-11.0.qcow2.xz
 ✓ Downloaded haos_ova-11.0.qcow2.xz
 ✓ Extracted KVM Disk Image
 ✓ Created HAOS VM (haos11.0)
 ✓ Started Home Assistant OS VM
 ✓ Completed Successfully!
```

**Comment by enoch85** [comment]
Ok, but what about redownloading the same file over and over?

**Comment by tteck** [comment]
There is no file saved, it's downloaded in a temporary directory and removed on exit.

**Comment by enoch85** [comment]
> There is no file saved, it's downloaded in a temporary directory and removed on exit.

I think you missed the point, but ok. :)

**Pull request closed without merging**
