### PR TITLE
Add new LXC: Open WebUI

### PR DESCRIPTION
**Pull request by havardthom**
> [!NOTE]
I am meticulous when it comes to merging code into the main branch, so please understand that I may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Requested: https://github.com/tteck/Proxmox/discussions/50#discussioncomment-10945387

Open WebUI is a feature-rich, and user-friendly self-hosted WebUI designed to operate entirely offline. It supports various LLM runners, including Ollama and OpenAI-compatible APIs. For more information, be sure to check out our [Open WebUI Documentation](https://docs.openwebui.com/).

No default user - signup process in WebUI.

Note: Install process is long, mostly due to PyTorch dependency, so I opted for CPU version of PyTorch which means users who want GPU support needs to install that themselves. Can also go for GPU version if you prefer that, guess it depends on if users want to run ollama in this LXC or a separate LXC, personally I would probably setup ollama as a separate LXC which Open WebUI calls. 

Some metrics for N100 Mini PC and 100 Mbps download speed:
```
With PyTorch CPU version
Total install time: 6:30 min
LXC storage use: 6 GB

With PyTorch GPU version
Total Install time: 11:30 min
LXC storage use: 13 GB

Adding ollama service
Additional install time: +3 min
Additional storage use: +4 GB
```

open-webui-installed
open-webui-updated
open-webui-login
open-webui-chat

## Type of change

Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [x] New script (a fully functional and thoroughly tested script or set of scripts.)
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Documentation update required (this change requires an update to the documentation)

### CODE REVIEW

**Comment by MickLesk** [comment]
RIP User Hardware :laughing: I specifically declined to do this LXC because I know how much resources are used and wasted with self-hosted LLAMAs.

**Comment by havardthom** [comment]
Installing a LXC is quite voluntary and a lot of users have hardware that can easily handle this. I wouldn't say this LXC put any strain on my resources, mostly bumped up default values just for the install process.

**Comment by MickLesk** [comment]
Well, what do you mean many people have the hardware for it? You don't need to start with an old Dell rack or anything else :satisfied: 
My current Minisforum UM790 Pro with 64GB of RAM (running multiple build pipelines in Docker and similar in the best case) is really struggling with it. Obviously only if you install LLAMAs on it, if you use the OpenAI API this is hardly an issue, but then you can also use the ChatGPT site ^^

https://github.com/tteck/Proxmox/discussions/3505#discussioncomment-10877057

**Comment by tteck** [comment]
That's one reason I haven't merged it yet. I'm considering all the potential issues and discussions that might arise. I don't want another Frigate situation. That being said, I'm still weighing the pros and cons.

**Comment by MickLesk** [comment]
> That's one reason I haven't merged it yet. I'm considering all the potential issues and discussions that might arise. I don't want another Frigate situation. That being said, I'm still weighing the pros and cons.

Pro:
1) It runs.
2) It looks good.
3) It works as it should.

Cons:
1) Custom LLAMA's via OLLAMA are damn slow
2) Devices without GPU are extremely slow
3) Devices with (a big) GPU are hard to maintain, that makes the script huge (even more than the HW transcoding tweak of your other LXC's) Nvidia runs better than AMD, Intel really bad, at least what I could test so far. 
4) even “small” LLAMA's like Mistral7b are sometimes extremely slow and kill the CPU in CPU mode, with very simple topics like “Name me 10 Bud Spencer movies” or similar. 
=> some Example run 15 to 30 sec, some example runs 30min :-D

**Comment by havardthom** [comment]
> > That's one reason I haven't merged it yet. I'm considering all the potential issues and discussions that might arise. I don't want another Frigate situation. That being said, I'm still weighing the pros and cons.
> 
> Pro:
> 
> 1. It runs.
> 2. It looks good.
> 3. It works as it should.
> 
> Cons:
> 
> 1. Custom LLAMA's via OLLAMA are damn slow
> 2. Devices without GPU are extremely slow
> 3. Devices with (a big) GPU are hard to maintain, that makes the script huge (even more than the HW transcoding tweak of your other LXC's) Nvidia runs better than AMD, Intel really bad, at least what I could test so far.
> 4. even “small” LLAMA's like Mistral7b are sometimes extremely slow and kill the CPU in CPU mode, with very simple topics like “Name me 10 Bud Spencer movies” or similar.
>    => some Example run 15 to 30 sec, some example runs 30min :-D

Sounds like you are running models that your system cannot handle. I'm currently running llama3.2:3B at ~9 tokens/sec and llama3.2:1B at ~14 tokens/sec and I am very happy with that performance considering I am just running it out-of-the-box without any optimization and without starting to look at hardware acceleration. This is on a N100 miniPC which is quite common in homelab setups.

Point is, there are many different models for different use cases and I am sure this LXC will provide value to many users. If this LXC will cause many issues or discussions I unfortunately can not predict.

**Comment by tteck** [comment]
I'm going to merge this, but not putting it on the website for now. Gotta test
Don't be surprised if it gets removed from the repo.

**Comment by bdrewery** [comment]
It works great until an update is done. During update `npm run build` hits java memory limits. I haven't found the required memory yet. Is there a way to pull a prebuilt image so we don't need so much more ram just for update?

**Comment by havardthom** [comment]
> It works great until an update is done. During update `npm run build` hits java memory limits. I haven't found the required memory yet. Is there a way to pull a prebuilt image so we don't need so much more ram just for update?

Did you install the LXC before this fix: https://github.com/tteck/Proxmox/commit/64eab60a4cfad9b1acf868691451a5ab0aff8fe6? You can try running this `export NODE_OPTIONS="--max-old-space-size=4096"` in LXC console before update

**Comment by bdrewery** [comment]
@havardthom Ah mine was missing that. Thanks.

**Comment by bdrewery** [comment]
@havardthom Using that did change the error to "Killed". Perhaps the limit needs to be slightly less since the LXC is built with 4096 memory, which isn't leaving room for shell/build process overhead that's not node heap/etc.

I raised my VM size to 5G ram and watched the memory use with the 4096 node limit. It hit at least 4.3gb memory used.
I tested with 512 buffer with limit set to 3584 and 4g ram and it builds fine.

Also might need the same env option added to ct/openwebui.sh?

**Pull request merged**
