### PR TITLE
Adding Transmisson Daemon container

### PR DESCRIPTION
**Pull request by andrimarjonsson**
# All Pull Requests should be made to the `pull-requests` branch

## Description
Adding scripts to setup a container for transmission-daemon.

## Type of change
- [ ] New feature 
- [ ] New Script

### CODE REVIEW

**Comment by tteck** [comment]
Sorry it's nonfunctional

**Comment by tteck** [comment]
If you're needing a Transmission LXC, I can create a working one. Just let me know.

**Comment by andrimarjonsson** [comment]
Yeah sorry about that, I was unsure about which "$var_install.sh" path I should pull request with.

Also since I have a pre-made config I just copy in right away I keep forgetting that transmission default config is a bit weird in that it does not work for basic local network access, only localhost access despite binding to 0.0.0.0

Simplest way to get it to work for local network access:
- Start the service, then stop it to generate the default settings.json
- sed script to disable both rpc-whitelist-enabled and rpc-host-whitelist-enabled
- Restart the service

or if you do not mind large echo commands, piping the following to `/etc/transmisson-daemon/settings.json` and then `chown debian-transmission:debian-transmission /etc/transmission-daemon/settings.json`
```
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/var/lib/transmission-daemon/downloads",
    "download-limit": 100,
    "download-limit-enabled": 0,
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/var/lib/transmission-daemon/Downloads",
    "incomplete-dir-enabled": false,
    "lpd-enabled": false,
    "max-peers-global": 200,
    "message-level": 1,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": false,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "{d198bfb7ededff9baa5f0c98f062b03e766916ffPgUDkdUw",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "transmission",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 18,
    "upload-limit": 100,
    "upload-limit-enabled": 0,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true
}
```

**Comment by tteck** [comment]
Exactly, working version at
```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/dev/ct/transmission-v5.sh)"
```

**Comment by andrimarjonsson** [comment]
Awesome!
Thank you for your understanding and I'll do better next time.

**Pull request merged**
