### PR TITLE
[WIP] Adding Kibana

### PR DESCRIPTION
**Pull request by Elkozel**
## Description
This provides two new scripts for Kibana, which are widely used for system and security monitoring. The added scripts are:

- ct/kibana.sh
- install/kibana-install.sh

Description about the files are below.

### ct/kibana.sh
The file provides a typical installation, based on the `adguard.sh` installation script provided without any changes.

### install/kibana-install.sh
This script follows the `n8n-install.sh` script, completing almost the same steps for installation using `apt-get`. 

## Fixes
No issues were created for this improvement.

## Type of change

Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [x] New script (a fully functional and thoroughly tested script or set of scripts.)
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Documentation update required (this change requires an update to the documentation)

### CODE REVIEW

**Comment by tteck** [comment]
This code is not correct, sorry.

**Comment by tteck** [comment]
- wrong font in header
- misuse of `$STD`
- missing flags
- incorrect `systemd` commands
- not adhering to the established patterns and conventions

**Comment by Elkozel** [comment]
Thank you very much for the feedback, I will address it

**Comment by tteck** [comment]
Is Elastic/Kibana FOSS?

**Comment by Elkozel** [comment]
I think so, both [Elastic](https://github.com/elastic/elasticsearch) and [Kibana](https://github.com/elastic/kibana) are released under the AGPLv3 license.

**Comment by Elkozel** [comment]
Also, could you please give me the font used for the header?

**Comment by tteck** [comment]
https://www.patorjk.com/software/taag/#p=display&f=Slant&t=Kibana

I don't think there is a free plan https://www.elastic.co/pricing

**Comment by Elkozel** [comment]
Thanks for the header font. 
I think the plans you're looking at are for the Elastic Cloud (every price has the suffix: "Based on cloud production config, 120 GB storage / 2 zones.")

**Comment by tteck** [comment]
Show me where it states that self hosting is free.

**Comment by Elkozel** [comment]
https://www.elastic.co/subscriptions
https://www.elastic.co/about/free-and-open

**Pull request closed without merging**
