### PR TITLE
Add netboot.xyz LXC scripts

### PR DESCRIPTION
**Pull request by leonelafonsoe**
## Description

Add netboot.xyz install scripts https://netboot.xyz/docs/selfhosting

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix 
- [ ] New feature 
- [x] New Script
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
Why is this a suitable candidate for inclusion in this repository? I've utilized similar tools before, albeit on a USB stick.
This appears to have the potential to be challenging from a support perspective.

**Comment by tteck** [comment]
I appreciate your efforts, but I'll have to decline incorporating this addition.

**Comment by leonelafonsoe** [comment]
No problem. It's ok if you don't find a useful use case. Thank you for all the scritps tho

**Comment by kittizz** [comment]
I’ve previously set up a bare-metal OS using a netboot.xyz LXC. I had initially created the netboot.xyz LXC myself but removed it after I was done using it. Now, I would like to use it again, and I believe having a script for this would make the process much more convenient.

**Pull request closed without merging**
