### PR TITLE
Added cosmetic changes

### PR DESCRIPTION
**Pull request by X-Anonymous-Y**
## Description

Please include a summary of the change and/or which issue is fixed. 

changed Cores text, added automatically detects (Core/s), added named values ​​for Disk, Core/s and RAM

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix 
- [x] New feature 
- [ ] New Script
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
Have you tested this to ensure displayed values work?

**Comment by X-Anonymous-Y** [comment]
> Have you tested this to ensure displayed values work?

```
Header
...
Using Default Settings
Using Distribution: alpine
Using alpine Version: 3.18
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 10042
Using Hostname: alpine
Using Tags: alpine
Using Disk Size: 0.5 GB
Allocated CPU: 1 Core
Allocated RAM: 512 MB
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
```

```
Using Default Settings
Using Distribution: alpine
Using alpine Version: 3.18
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 10043
Using Hostname: alpine
Using Tags: alpine
Using Disk Size: 0.5 GB
Allocated CPU: 4 Cores
Allocated RAM: 512 MB
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
```

**Comment by X-Anonymous-Y** [comment]
> > Have you tested this to ensure displayed values work?
> 
> ```
> Header
> ...
> Using Default Settings
> Using Distribution: alpine
> Using alpine Version: 3.18
> Using Container Type: 1
> Using Root Password: Automatic Login
> Using Container ID: 10042
> Using Hostname: alpine
> Using Tags: alpine
> Using Disk Size: 0.5 GB
> Allocated CPU: 1 Core
> Allocated RAM: 512 MB
> Using Bridge: vmbr0
> Using IP Address: dhcp
> Using Gateway Address: Default
> Disable IPv6: no
> Using Interface MTU Size: Default
> Using DNS Search Domain: Host
> Using DNS Server Address: Host
> Using MAC Address: Default
> Using VLAN Tag: Default
> Enable Root SSH Access: no
> Enable Verbose Mode: no
> ```
> 
> ```
> Using Default Settings
> Using Distribution: alpine
> Using alpine Version: 3.18
> Using Container Type: 1
> Using Root Password: Automatic Login
> Using Container ID: 10043
> Using Hostname: alpine
> Using Tags: alpine
> Using Disk Size: 0.5 GB
> Allocated CPU: 4 Cores
> Allocated RAM: 512 MB
> Using Bridge: vmbr0
> Using IP Address: dhcp
> Using Gateway Address: Default
> Disable IPv6: no
> Using Interface MTU Size: Default
> Using DNS Search Domain: Host
> Using DNS Server Address: Host
> Using MAC Address: Default
> Using VLAN Tag: Default
> Enable Root SSH Access: no
> Enable Verbose Mode: no
> ```


Advanced Settings
```
Using Distribution: alpine
Using alpine Version: 3.18
Using Container Type: 1
Using Root Password: P * * * d
Container ID: 10044
Using Hostname: alpine
Using Tags: alpine
Using Disk Size: 0.5 GB
Allocated CPU: 1 Cores
Allocated RAM: 512 MB
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: yes
Added SSH-Key: no
Enable Verbose Mode: no
```


```
Using Distribution: alpine
Using alpine Version: 3.18
Using Container Type: 1
Using Root Password: P * * * d
Container ID: 10044
Using Hostname: alpine
Using Tags: alpine
Using Disk Size: 1 GB
Allocated CPU: 4 Cores
Allocated RAM: 2048 MB
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: no
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using Vlan: Default
Enable Root SSH Access: yes
Added SSH-Key: no
Enable Verbose Mode: no
```

**Comment by X-Anonymous-Y** [comment]
As you can see in the advanced settings, I made some changes ;)

Such as the password (you can see first and last char) or Add SSH-Key if enabled SSH "Added SSH-Key: ssh-rsa * * * X-Anonymous-Y@X-Anonymous-Y-Desktop"

**Comment by tteck** [comment]
Advanced settings show `Allocated CPU: 1 Cores` instead of `Allocated CPU: 1 Core`
`echo -e "${DGN}Allocated Ram ${BGN}$var_ram${CL} ${CL}${DGN}MB${CL}"` double `${CL}`
While I appreciate your efforts, the password was left visible on purpose. 
Why add `Added SSH-Key: no` if there is no option to add one?
I think I'll leave it the way it is, sorry.

**Comment by X-Anonymous-Y** [comment]
> Advanced settings show `Allocated CPU: 1 Cores` instead of `Allocated CPU: 1 Core` `echo -e "${DGN}Allocated Ram ${BGN}$var_ram${CL} ${CL}${DGN}MB${CL}"` double `${CL}` While I appreciate your efforts, the password was left visible on purpose. Why add `Added SSH-Key: no` if there is no option to add one? I think I'll leave it the way it is, sorry.

So now I tested it all again! everything is displayed correctly! I didn't add the changes to the password and SSH keys here! I added a function to my local scripts for this. The only thing that isn't nice is: the double ${CL}, that's true, but I'm happy to change that! Unless you don't want that changed at all.

```
Using Default Settings
Using Distribution: alpine
Using alpine Version: 3.18
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 10044
Using Hostname: alpine
Using Tags: alpine
Using Disk Size: 1 GB
Allocated CPU: 1 Core
Allocated RAM: 1024 MB
```

```
Using Default Settings
Using Distribution: alpine
Using alpine Version: 3.18
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 10044
Using Hostname: alpine
Using Tags: alpine
Using Disk Size: 2 GB
Allocated CPU: 2 Cores
Allocated RAM: 2048 MB
```

```
Using Advanced Settings
Using Distribution: alpine
Using alpine Version: 3.18
Using Container Type: 1
Using Root Password: P * * * d
Container ID: 10044
Using Hostname: alpine
Using Tags: alpine
Using Disk Size: 3 GB
Allocated CPU: 3 Cores
Allocated RAM: 3000 MB
```

```
Using Advanced Settings
Using Distribution: alpine
Using alpine Version: 3.18
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 10044
Using Hostname: alpine
Using Tags: alpine
Using Disk Size: 0.5 GB
Allocated CPU: 1 Core
Allocated RAM: 4096 MB
```

**Pull request closed without merging**
