### PR TITLE
Add new LXC: Cockpit

### PR DESCRIPTION
**Pull request by havardthom**
> [!NOTE]
I am meticulous when it comes to merging code into the main branch, so please understand that I may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description
[Cockpit](https://cockpit-project.org/) is an easy-to-use, integrated, glanceable, and open web-based interface for servers. It is highly extensible and a popular choice for setting up fileservers on Proxmox (mostly due to the following guide from apalrd: https://www.apalrd.net/posts/2023/ultimate_nas/). It has also been requested in https://github.com/tteck/Proxmox/discussions/50#discussioncomment-10960061

The script allows optionally installing the following Cockpit modules used for setting up a fileserver:
45Drives Cockpit File Sharing - https://github.com/45Drives/cockpit-file-sharing
45Drives Cockpit Identities - https://github.com/45Drives/cockpit-identities/
45Drives Cockpit Navigator - https://github.com/45Drives/cockpit-navigator

cockpit-lxc-created
cockpit-applications
cockpit-file-sharing
cockpit-identities
cockpit-navigator
cockpit

## Type of change

Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [x] New script (a fully functional and thoroughly tested script or set of scripts.)
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Documentation update required (this change requires an update to the documentation)

### CODE REVIEW

**Comment by havardthom** [comment]
Fixed typo in msg_ok: `Installing dependencies` -> `Installed dependencies`

**Comment by tteck** [comment]
Nice! Thanks

**Comment by tteck** [comment]
I don’t see the added value in having a dedicated LXC container for Cockpit, since it can just be installed on an existing LXC, similar to how Webmin is typically set up.

Please help me understand.

**Comment by havardthom** [comment]
It is commonly used as a dedicated LXC for filesharing, passing through storage mount points and setting up Samba shares/NFS in Cockpit (As per apalrd's guide https://youtube.com/watch?v=Hu3t8pcq8O0). Personally I have a single LXC with only Cockpit installed which handles all my shared storage. 

Though Cockpit is just a web interface for servers, so I understand your point that it could be useful on any existing LXC.

**Pull request merged**
