### PR TITLE
Added cleanupDockerImages script.

### PR DESCRIPTION
**Pull request by SamTV12345**

### CODE REVIEW

**Comment by tteck** [comment]
You'll have to explain what this is for?

**Comment by SamTV12345** [comment]
This script is used to cleanup old images. When using e.g. [watchtower](https://containrrr.dev/watchtower/) there is the issue that old images aren't cleaned up. So the used space in lxc containers grows continually. This script iterates over all containers, checks if docker is installed and if yes, it cleans up all unused images.

**Comment by tteck** [comment]
These scripts don't use docker containers (Except for the Home Assistant Container LXC)

**Comment by SamTV12345** [comment]
Ok. I just stumbled upon your update lxc container script and updated it to fit my needs. If the script is not needed I'll close the pull request.

**Comment by tteck** [comment]
Thanks for the suggestion, but script not needed.

**Pull request closed without merging**
