### PR TITLE
Alpine ddclient LXC Script

### PR DESCRIPTION
**Pull request by nicedevil007**
## Description

Created a new LXC Script with the DDClient application that is available on Alpine Linux.
This tool is used for syncing your IP with a DynDNS Provider (there are a lot implemented).

One small downside is the not existing WebUI. In my case it is working rocksolid since 6 years now.

Link to stock software with further information: https://github.com/ddclient/ddclient
Alpine Linux Guide for Deployment: https://wiki.alpinelinux.org/wiki/Ddclient

Because it is not using a WebUI I changed the last echo command a bit @tteck (I hope that was ok?)
Also to get the user up and running I made the motd change with the command the user should use in the shell then.
Ofc we can get rid of that but maybe it helps most users.

To update this Application we only have to run the stock
```python
apk update && apk upgrade
```

Ofc I made the same Update Menu as on my first 2 scripts for alpine with the addition to change the update schedule for ddclient :)

PS: yes I can reupload if you want because of the other commits that are not in your pull requests branch.

## Screenshots

Ressoruce Cost:
image

## Type of change

Please delete options that are not relevant.

- [X] New Script
- [X] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
Don't know if I'm interested in adding this to the repo.

**Comment by tteck** [comment]
Oops, created fresh pull-requests branch

**Comment by nicedevil007** [comment]
> Don't know if I'm interested in adding this to the repo.

why not? Because of the lack of the WebUI?
I guess most of the guys using all those LXCs don't have a static IP adress and all of them will be using a dynamic DNS thingi.

At least not all routers have full support for all dynDNS providers out there and this one made it really easy in my opinion to include the most ones.

Btw: the /etc/ddclient/ddclient.conf has a lot examples in it to get an idea of how to start.

**Comment by tteck** [comment]
I believe that this container would be overwhelming in meeting the required level of assistance needed to cater to users' needs, which is the crucial factor.

**Comment by nicedevil007** [comment]
> I believe that this container would be overwhelming in meeting the required level of assistance needed to cater to users' needs, which is the crucial factor.

mhhh I understand your point. But I don't have the skills to understand and use grafana or influxdb out of the box and had to read through guides to not mess up those LXCs. That will always be the case if we are new to anything or?

here an example config for `dedyn.io` => you can get those for free here https://desec.io

I have a subdomain on my dns provider => `mysubdomain.dedyn.io` and after creating it I got the password/token from them like `hQXiCpt973C7XHb8oYaeK9EAnEbga9`

just the last 3 lines must be changed to this... ofc I can script this as well if you want to make it even easier?

```python
protocol=dyndns2
use=if, if=eth0
ssl=yes
use=cmd, cmd='curl https://checkipv4.dedyn.io/'
server=update.dedyn.io
login=mysubdomain.dedyn.io
password='hQXiCpt973C7XHb8oYaeK9EAnEbga9'
mysubdomain.dedyn.io
```

**Comment by tteck** [comment]
It's essential to distinguish between the intention to acquire knowledge independently using these scripts and the assumption that I'll provide assistance with the configuration. It's frustrating when people become upset if I'm unable to offer support. This is solely a hobby for me, and I must ensure that it doesn't turn into a job.
Nonetheless, I want to express my appreciation for the effort and dedication you put into this project.

**Pull request closed without merging**
