### PR TITLE
Added Bookstack LXC

### PR DESCRIPTION
**Pull request by javedh-dev**
## Description

Add new script for [Bookstack](https://www.bookstackapp.com/). BookStack is a simple, self-hosted, easy-to-use platform for organising and storing information.

## Type of change

Please delete options that are not relevant.

- [x] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [x] I have performed a self-review of my code, adhering to established codebase patterns and conventions.

### CODE REVIEW

**Comment by tteck** [comment]
There is a Bookstack LXC already available via TurnKey
https://github.com/tteck/Proxmox/blob/0a35b1a5bb3bb8c61aa1e8f95e14048667263101/turnkey/turnkey.sh#L69

**Comment by javedh-dev** [comment]
@tteck Thanks for the response but I personally don't prefer turnkey LXC's. That's why created on bare debian image. But sure if that is not required. Please close this PR.

**Comment by tteck** [comment]
Does the script run silent? No verbose.

**Comment by javedh-dev** [comment]
> Does the script run silent? No verbose.

Yes It runs silent. one small change I'll push.

**Comment by OddSquirrel** [comment]
Tbh, I much prefer the scripts on here to TurnKey. The latter works just fine, but it doesn't support in-place upgrades, leading to lots of fumbling around at a later point in time. I'd honestly rather spin up a Docker container and be done with it. 😒

**Comment by tteck** [comment]
Default dependencies are missing
The command `mysql` is deprecated in MariaDB https://github.com/tteck/Proxmox/issues/2993
MariaDB credentials should be stored in a `.creds` file
PHP should be its own section
`BOOKSTACK_DIR="/opt/bookstack"` should not be used so that the code is easier to follow
There are still many more things to fix. For now, I'm going to put this on the backburner. I may revisit it later as time allows

**Pull request closed without merging**
