### PR TITLE
AdGuardHome-Alpine LXC

### PR DESCRIPTION
**Pull request by nicedevil007**
## Description

I created an Alpine-LXC Script based on your vaultwarden script with the changes needed for AdGuardHome.
Since Alpine doesn't have a systemd resolver running, no error message or even more scripting is needed :)

Less Storage, less Memory, Less CPU needed and ofc less time on first installation... not that much but everything counts right :)

## Screenshots
AdGuardHome with debian
image

AdGuardHome with alpine
image

## Documentation for Update Process
Can be updated with the script inside the container or even less complicated directly in the WebUI :)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix 
- [ ] New feature 
- [x] New Script
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by tteck** [comment]
Did you try running the script's update section? It appears that when using `wget` in Alpine, the `-L` option is not recognized.

**Comment by nicedevil007** [comment]
It wasn't running on my first script, but I thought it was on my latest commit to my PR... will test again tomorrow :)

**Comment by tteck** [comment]
Based on the `.png` you shared, I recommend reducing the storage capacity to 200MiB.

**Comment by nicedevil007** [comment]
> Based on the `.png` you shared, I recommend reducing the storage capacity to 200MiB.

That was done by purpose. The screenshots are made by a complete fresh installation without any logged data to get a comparison => "close to the same starting point".

I have multiple adguards running on different servers of my friends. One of them got about 300.000 queries each day and that can fill up the log quite fast. He got around 2 gb on his bootdrive.

I know we can say that this is what the user can decide by himself. In my opinion I just wanted to start with good amount of space for logs. The ressource of storage capacity isn't the most valuable one on a server these days right? :P 

I changed it to the `300 MB` you got in your vaultwarden LXC with alpine now. At least making it bigger isn't a huge deal later on.

Thats why I opened a discussion a bit ago here: https://github.com/tteck/Proxmox/discussions/1134

Oh during my testing I tried running the script locally in the alpine LXC itself instead of the lxc-attach command from the host.

You use this to decapitalize a string on all your commands 

```python
NSAPP=$(echo ${APP,,} | tr -d ' ')
```
I changed it on the adguard script now to this:
```python
NSAPP=`echo "${APP}" | tr '[A-Z]' '[a-z]'`
```
This will work on more shells :) (can't test all, but it was working on ash, bash)

**Comment by tteck** [comment]
Regarding `NSAPP`, my command converts the entire string to lowercase and then removes any spaces, while your command only converts uppercase characters to lowercase.

Just loose the `-L` flag, keeping `wget`

`mc` is a base dependency in all LXCs.

The `--no-cache` flag isn't necessary.

It seems that you intend to modify many things that do not adhere to my consistent rule across all LXCs. This would necessitate me changing them back to their original state.

**Comment by nicedevil007** [comment]
> Regarding `NSAPP`, my command converts the entire string to lowercase and then removes any spaces, while your command only converts uppercase characters to lowercase.
> 
> Just loose the `-L` flag, keeping `wget`
> 
> `mc` is a base dependency in all LXCs.
> 
> The `--no-cache` flag isn't necessary.
> 
> It seems that you intend to modify many things that do not adhere to my consistent rule across all LXCs. This would necessitate me changing them back to their original state.

Just wanted to make it more compatible with drivates of linux :) I can change these lines of codes back and use wget ofc.

BTW: Did you ever tried making it possible to include a SSH-Pub Key during your installation?

**Comment by tteck** [comment]
What's going on here https://github.com/tteck/Proxmox/pull/1181/commits/093d7241b57c9a5efe038c13e124d0bff2bf804c starting at line 390?

1) Removed whiptail menu with no option?
2) Changed from checking directory to checking file?

**Comment by nicedevil007** [comment]
> What's going on here [093d724](https://github.com/tteck/Proxmox/commit/093d7241b57c9a5efe038c13e124d0bff2bf804c) starting at line 390?
> 
> 1. Removed whiptail menu?
> 2. Changed from checking directory to checking file?

I made those changes like you did on your vaultwarden?
there is no whiptail menu for the vaultwarden stuff and you did the check against the `/etc/conf.d/vaultwarden` what is also a file? ofc we can do the check against the directory but I thought the binary is good as well
=> https://github.com/tteck/Proxmox/blob/main/ct/alpine-vaultwarden-v5.sh line 407..409

Mhh I figured out that the whiptail menu isn't possible in alpine linux, it is skipping this part directly and says "User exited script"

On Vaultwarden you did an other menu, I will adopt to this if that is ok for you?
On my last grafana LXC there wasn't a whiptail as well... ok there we only need to update the alpine packages with `apk upgrade`... let me provide you a menu with your part of the vaultwarden stuff.

**Comment by tteck** [comment]
Why https://github.com/tteck/Proxmox/pull/1181/commits/e1623e210492744906733b53fb831361dd9c068e? 
In case you update before setting up AdGuard?

So, replacing `if test -f "/opt/AdGuardHome/AdGuardHome.yaml"; then` with `if [ -f "/opt/AdGuardHome/AdGuardHome.yaml" ]; then` would be a more conventional and preferred way to write the script. But, I'm confused as to why it's needed.

**Comment by tteck** [comment]
>ofc we can do the check against the directory but I thought the binary is good as well

Keep it consistent with the other AdGuardHome install method.

> I figured out that the whiptail menu isn't possible in alpine linux,

You are correct.

>On Vaultwarden you did an other menu, I will adopt to this if that is ok for you?

Perfect

**Comment by nicedevil007** [comment]
> Why [e1623e2](https://github.com/tteck/Proxmox/commit/e1623e210492744906733b53fb831361dd9c068e)? In case you update before setting up AdGuard?
> 
> So, replacing `if test -f "/opt/AdGuardHome/AdGuardHome.yaml"; then` with `if [ -f "/opt/AdGuardHome/AdGuardHome.yaml" ]; then` would be a more conventional and preferred way to write the script. But, I'm confused as to why it's needed.

you can try it on your "stock" debian script as well => sould lead to an error on cp -r  (I tried to get the output to &>/dev/null but didn't work for me)

=> ok menu is already done (should I do it for you on grafana as well?)

**Comment by tteck** [comment]
>you can try it on your "stock" debian script as well => sould lead to an error on cp -r

But, why would anyone try updating a newly created AdGuardHome LXC before setting it up?

In my opinion, this code is unnecessary.

**Comment by tteck** [comment]
And if you're going to use it, 

```
            if [ -f "/opt/AdGuardHome/AdGuardHome.yaml"]; then
                mkdir -p adguard-backup
                cp -r /opt/AdGuardHome/AdGuardHome.yaml /opt/AdGuardHome/data adguard-backup/
                cp AdGuardHome/AdGuardHome /opt/AdGuardHome/AdGuardHome
                cp -r adguard-backup/* /opt/AdGuardHome/
            else
                msg_error "${APP} has not been setup."
                rm -rf AdGuardHome_linux_amd64.tar.gz
                /opt/AdGuardHome/AdGuardHome -s start &>/dev/null
                exit
            fi
```

**Comment by tteck** [comment]
After thinking for a bit, you could just use:
```
cp -rf /opt/AdGuardHome/AdGuardHome.yaml /opt/AdGuardHome/data adguard-backup/
```
 The `-f` flag is used to force the copy operation. So, even if the source file does not exist, the `cp` command will not throw an error and will simply continue to the next file/directory to be copied.

**Comment by nicedevil007** [comment]
> After thinking for a bit, you could just use:
> 
> ```
> cp -rf /opt/AdGuardHome/AdGuardHome.yaml /opt/AdGuardHome/data adguard-backup/
> ```
> 
> The `-f` flag is used to force the copy operation. So, even if the source file does not exist, the `cp` command will not throw an error and will simply continue to the next file/directory to be copied.

wohoo that makes even more sense :) just keeping it simple

For the question: Why a user should run the script without prior going through the setup?
That is a lesson I learned from my work where I scripted other parts for colleques... they generate situations that we can't think about and I try to do a script that get all errors handled a user can make :P

**Comment by tteck** [comment]
You want this one?
https://wiki.alpinelinux.org/wiki/Nextcloud

**Comment by nicedevil007** [comment]
> You want this one?
> 
> https://wiki.alpinelinux.org/wiki/Nextcloud

That would be much more awesome than the version with the Raspberry Thing 💪

But that need a lot more work.
I already tried my best on scripting the creation of a database... you remember tandoor? Wasn't really successful... maybe I'm able to do it now?

So you want to start the NC project or should I do my first step into it?

**Comment by nicedevil007** [comment]
mhhh @tteck 
I'm testing an All in One solution to update with one script everything or even let the user choose if he wants run all scripts inside a container.... I found out that the cp -rf seems still not to work properly

image

btw do you have discord or anything like that, maybe it is easier to communicate with you there?

**Comment by tteck** [comment]
𝙩𝙩𝙚𝙘𝙠𝙨𝙩𝙚𝙧#7481

Everything is getting ready to change, look at the next branch

**Pull request merged**
