### PR TITLE
Add Forgejo LXC

### PR DESCRIPTION
**Pull request by barremian**
## Description

Add new script for [Forgejo](https://forgejo.org/). Forgejo is a GIT based distributed version control system forked from Gitea.

## Type of change

- [x] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [x] I have performed a self-review of my code, adhering to established codebase patterns and conventions.

### CODE REVIEW

**Comment by tteck** [comment]
For a start:
1) What about using SQLite and dropping the rest of the DB code?
2) "msg_ok" has its own color scheme, not to be changed. (which will be removed by 1.)
3) Try not to use "&&"

**Comment by barremian** [comment]
Hi @tteck, thanks for the review.
1. I see what you're getting at. The Forgejo team suggests SQLite must suffice for [upto 10 users](https://forgejo.org/docs/v1.20/admin/installation/#optional-set-up-database), but it should be mostly enough for users of the script. I've removed the database selection snippets.
2. Solved by 1.
3. `&&` have been removed.

**Comment by tteck** [comment]
Remove
```
echo "" >>~/forgejo.creds
echo -e "Forgejo GIT User: \e[32mgit\e[0m" >>~/forgejo.creds
echo -e "Forgejo data directory: \e[32m/var/lib/forgejo\e[0m" >>~/forgejo.creds
```
Will be in the instructions

Change to
```
systemctl enable -q --now forgejo
```

Change to
```
$STD apt-get -y autoremove
$STD apt-get -y autoclean
```

**Comment by barremian** [comment]
Done

**Comment by tteck** [comment]
Thanks

**Comment by icf20** [comment]
i tested this and imo 

1 the db setup selection needs to be done on the install and add PostgreSQL LXC like an optional install 

or

2 in the script description state it needs PostgreSQL LXC

**Comment by tteck** [comment]
https://forgejo.org/docs/latest/admin/installation-binary/#optional-set-up-database
> When using sqlite as Forgejo’s database, nothing needs to be done here.
If you need a more powerful database, you can use MySQL/MariaDB or PostgreSQL (apparently sqlite is good enough for at least 10 users, but might even suffice for more).

**Comment by icf20** [comment]
sure but is meh, literally meh, forgero is a fork of gitea, and you already have a script for turnkey gitea

**Pull request merged**
