### PR TITLE
Add new LXC: Silverbullet

### PR DESCRIPTION
**Pull request by ewilazarus**
## Description

If applied, this PR will add a new LXC for running [Silverbullet](https://github.com/silverbulletmd/silverbullet).

> SilverBullet is a note-taking application optimized for people with a [hacker mindset](https://en.wikipedia.org/wiki/Hacker). We all take notes. There’s a million note taking applications out there. [Literally](https://www.noteapps.ca/). Wouldn’t it be nice to have one where your notes are more than plain text files? Where your notes essentially become a database that you can query; that you can build custom knowledge applications on top of? A hackable notebook, if you will?

The code has been tested by invoking 

```
bash -c "$(wget -qLO - https://github.com/ewilazarus/Proxmox/raw/silverbullet-test/ct/silverbullet.sh)"
```

Where `silverbullet-test` is a branch with [these minor differences](https://github.com/ewilazarus/Proxmox/compare/silverbullet..silverbullet-test).

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [x] I have performed a self-review of my code, adhering to established codebase patterns and conventions.
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by ewilazarus** [comment]
Silverbullet discourse topic: 

https://community.silverbullet.md/t/silverbullet-running-in-proxmox-lxc/565?u=ewilazarus

**Comment by tteck** [comment]
The code does not adhere to the established patterns and conventions throughout the codebase.

**Comment by ewilazarus** [comment]
@tteck, can you please elaborate? 

I'd be happy to modify the PR to make it compliant to the established patterns and conventions.

👍

**Comment by tteck** [comment]
I'd suggest taking the time to review some of the merged Pull Requests.

**Comment by ewilazarus** [comment]
Sounds good. I'll take a look and create a 2nd PR attempt.

**Pull request closed without merging**
