### PR TITLE
Create kali 2024.1 VM

### PR DESCRIPTION
**Pull request by CrazyWolf13**
## Description

I created a VM for kali linux, I chose the GUI-Installer, for myself, but you may change this to the desired best-fitting image for this repository.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New Script (Develop a new script or set of scripts that are fully functional and thoroughly tested)
- [x] I have performed a self-review of my code, adhering to established codebase patterns and conventions.
- [x] This change requires a documentation update

### CODE REVIEW

**Comment by CrazyWolf13** [comment]
Not ready yet.

**Comment by CrazyWolf13** [comment]
Should be ready now :)

**Comment by tteck** [comment]
is this a cloud-init image?

**Comment by CrazyWolf13** [comment]
> is this a cloud-init image?

No it's normal GUI image, I chose for myself.

If you think another image may fit better, here  is a list.
https://www.kali.org/get-kali/#kali-cloud

**Comment by tteck** [comment]
The script is misconfigured.

**Comment by CrazyWolf13** [comment]
> The script is misconfigured.

Hi
I totally accept that, but could you be a bit more specific, what exactly is miscongifured?

**Comment by tteck** [comment]
The script is set to use a cloud-init image.You stated the image wasn't cloud-init. Yet at the end of the script it says "Setup Cloud-Init before starting" and gives a link to set up a cloud-init Ubuntu VM. Simply changing the image download link in an existing script doesn't typically add much value to the repository.

**Pull request closed without merging**
