### PR TITLE
Add new LXC: Ollama

### PR DESCRIPTION
**Pull request by havardthom**
> [!NOTE]
I am meticulous when it comes to merging code into the main branch, so please understand that I may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

[Ollama](https://ollama.com/) is an application for running large language models (LLMs) locally on your computer, focusing on ease of setup and performance. It allows users to install, manage, and interact with advanced language models, including models like LLaMA and other fine-tuned variations, directly on their own hardware without needing to rely on cloud-based services.

Script supports Intel GPU passthrough - Ollama fallbacks to CPU LLM runner if no GPU is found.

Alternative for quicker install: Pull Ollama compiled binary executable instead of building from source, but that does not support Intel GPU passthrough.

Install metrics for N100 Mini PC and 100 Mbps download speed:
```
Installing Intel® oneAPI Base Toolkit: ~8 min
Installing Ollama: ~10 min
Total LXC install time: ~20 min

LXC storage use: 19.36 GiB
```

ollama-installed
ollama-running
ollama-loga
ollama-in-webui

## Type of change

Please check the relevant option(s):

- [ ] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [x] New script (a fully functional and thoroughly tested script or set of scripts.)
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Documentation update required (this change requires an update to the documentation)

### CODE REVIEW

**Comment by tteck** [comment]
How much time is needed for the complete install?

**Comment by havardthom** [comment]
> How much time is needed for the complete install?

Around 20 min, as mentioned in the PR description

**Comment by tteck** [comment]
35 minutes here, after installation, what's next?

**Comment by havardthom** [comment]
You can pull LLM models and use them with the Ollama API

For a quicker install I can alternatively add Intel GPU passthrough as a optional install instead

**Comment by havardthom** [comment]
I would recommend using Open WebUI since it has a great integration with Ollama API

Screenshot 2024-10-27 122534
Screenshot 2024-10-27 122557

**Comment by tteck** [comment]
Where are you getting the API key?

**Comment by havardthom** [comment]
Ollama API only needs URL to the LXC. The OpenAI API needs a key that can be generated here https://platform.openai.com/api-keys, but the OpenAI API is not free.

**Comment by tteck** [comment]
How do I connect Ollama (your script) to Open WebUI (your script)?

**Comment by havardthom** [comment]
Add Ollama LXC URL to "Ollama API" under "Connections" settings in Open WebUI

image

**Comment by tteck** [comment]
I do not have to select a model?

Screenshot 2024-10-27 7 56 28 AM

**Comment by havardthom** [comment]
Find the model you want on https://ollama.com/library , write it in the search box, e.g. "llama3.2:1b" and select "Pull from Ollama.com" to download the model locally. After that you can select and use the model

**Comment by tteck** [comment]
All of this runs locally?
This may be difficult to explain to users as I don't have good documentation writing skills

**Comment by havardthom** [comment]
Yes it runs locally. There are also other apps that can utilize Ollama API, so it is not exclusively used for Open WebUI, though it is a very common use-case. 
I think it would be best to mention on [Open WebUI LXC docs](https://tteck.github.io/Proxmox/#open-webui-lxc) that Ollama API is not installed but can be hosted as a separate LXC (with a link to https://tteck.github.io/Proxmox/#ollama) 

How to connect and run Ollama API in Open WebUI people should find themselves in the application docs / internet

**Comment by havardthom** [comment]
It could also be mentioned on Ollama LXC doc that it exposes an API and does not provide an UI and for example link to supported UI's here https://github.com/ollama/ollama#web--desktop

**Comment by tteck** [comment]
> For a quicker install I can alternatively add Intel GPU passthrough as a optional install instead

How much quicker?

**Comment by havardthom** [comment]
> > For a quicker install I can alternatively add Intel GPU passthrough as a optional install instead
> 
> How much quicker?

Only building Ollama and not needing `intel-basekit` would probably cut install time in half. There is also an already compiled binary executable of Ollama available for download, but that only has Nvidia and AMD GPU support. Ollama must be built with `intel-basekit` for Intel support.

**Comment by tteck** [comment]
I'm thinking that eliminating the Intel stuff and using the Ollama binary, we could consider making it an option in the Open WebUI script.

**Comment by tteck** [comment]
The OS would need to match

**Comment by havardthom** [comment]
Alright, so you mean not having a separate Ollama LXC, but giving an option to add Ollama binary to Open WebUI script? And without hardware acceleration?

**Comment by tteck** [comment]
Yes, what are your thoughts?

**Comment by havardthom** [comment]
Sounds reasonable, still possible to expose Ollama from Open WebUI LXC for people that want to use it elsewhere, and people with GPU's can set up hardware acceleration themselves

**Comment by tteck** [comment]
Do you want to give it a try? If so, I'm ready to merge. lol

**Comment by havardthom** [comment]
Yes I'll have a look

**Comment by tteck** [comment]
https://github.com/ollama/ollama/blob/main/docs/linux.md#manual-install

**Pull request merged**
